### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by sonnysavage** [jojobrogess/script.deskpifanservice#1]
I would like to try this out, but I'm not sure how to install it.

**Comment by jojobrogess** [comment]
It's been a little bit since I've done this, so I might be wrong but: 

Download it from the repo, put it on a usb, put usb in kodi machine, open usb in the kodi file manager and install it. 

Then go into addon settings and click on the addon settings page, (I have forgotten how I set up the tabs) go to the first tab(the one on top) install all. 

After that go to the second(or middle tab) and select how you'd like the fan to run(constant or variable) and input the values you'd want. Then go back and run the addon. 

(Running the addon takes the values you set in the settings and applies them to the Deskpi software.)


Yah that was a terrible explanation, I'm sorry lol. I can create a more detailed set of instructions with photos, if you'd like?

**Comment by sonnysavage** [comment]
I ended up using the install instructions from here: https://github.com/jojobrogess/Libreelec-Deskpi-Installer

Is the installed code identical otherwise to the plugin? I'm seeing an error about the power button control when I shut down.

**Comment by sonnysavage** [comment]
I'm pretty sure the error I was seeing was because of [the issue I opened on your other repo](https://github.com/jojobrogess/Libreelec-Deskpi-Installer/issues/3). I've also created a [PR](https://github.com/jojobrogess/Libreelec-Deskpi-Installer/pull/4).

**Comment by jojobrogess** [comment]
Yea I wrote the addon version of the installer incorrectly the first time, I probably wrote the CLI version incorrect as well. 

New version should work perfectly. And I merged in the commit you had on the other repo(https://github.com/jojobrogess/Libreelec-Deskpi-Installer/pull/4).

Thank you
